Improved Makefile, Metrics, L1, L2, Database.

diff --git a/ansible/Makefile b/ansible/Makefile
--- a/ansible/Makefile
+++ b/ansible/Makefile
@@ -1,35 +1,54 @@
 .PHONY: all
 
+help:
+	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {if ($$1 ~ /^__/) printf "\033[33m%-50s\033[0m %s\n", $$1, $$2; else printf "\033[36m%-50s\033[0m %s\n", $$1, $$2}'
+
 all: inventory ethrex-l2
 
-inventory:
-	@if [ -z "$(DATABASE_IP)" ] || [ -z "$(L1_IP)" ] || [ -z "$(L2_IP)" ] || [ -z "$(MONITORING_IP)" ] || [ -z "$(EXPLORER_IP)" ]; then echo "Error: All variables (ETHREX_L1, ETHREX_L2, DATABASE, MONITORING, EXPLORER) must be set.\n\n  Usage: make inventory ETHREX_L1='ip1,ip2,...' ETHREX_L2='ip1,ip2,...' DATABASE='ip1,ip2,...' MONITORING='ip1,ip2,...' EXPLORER='ip1,ip2,...' \n" 1>&2; exit 1; fi; \
-	truncate -s0 inventory.ini
-	echo "[database]" >> inventory.ini; \
-	for ip in $$(echo $(DATABASE_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
-	echo "" >> inventory.ini; \
-	echo "[explorer]" >> inventory.ini; \
-	for ip in $$(echo $(EXPLORER_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done
-	echo "" >> inventory.ini; \
-	echo "[l1]" >> inventory.ini; \
-	for ip in $$(echo $(L1_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
-	echo "" >> inventory.ini; \
-	echo "[l2]" >> inventory.ini; \
-	for ip in $$(echo $(L2_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
-	echo "" >> inventory.ini; \
-	echo "[metrics]" >> inventory.ini; \
-	for ip in $$(echo $(METRICS_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o ForwardAgent=yes'" >> inventory.ini; done; \
-	
+inventory: ## Generates inventory for ansible
+	@if [ -n "$(DATABASE_IP)" ] || [ -n "$(EXPLORER_IP)" ] || [ -n "$(L1_IP)" ] || [ -n "$(L2_IP)" ] || [ -n "$(MONITORING_IP)" ]; then \
+		truncate -s0 inventory.ini; \
+		if [ -n "$(DATABASE_IP)" ]; then \
+			echo "[database]" >> inventory.ini; \
+			for ip in $$(echo $(DATABASE_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
+			echo "" >> inventory.ini; \
+		fi; \
+		if [ -n "$(EXPLORER_IP)" ]; then \
+			echo "[explorer]" >> inventory.ini; \
+			for ip in $$(echo $(EXPLORER_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=app ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
+			echo "" >> inventory.ini; \
+		fi; \
+		if [ -n "$(L1_IP)" ]; then \
+			echo "[l1]" >> inventory.ini; \
+			for ip in $$(echo $(L1_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=app ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
+			echo "" >> inventory.ini; \
+		fi; \
+		if [ -n "$(L2_IP)" ]; then \
+			echo "[l2]" >> inventory.ini; \
+			for ip in $$(echo $(L2_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=app ansible_python_interpreter=/usr/bin/python3" >> inventory.ini; done; \
+			echo "" >> inventory.ini; \
+		fi; \
+		if [ -n "$(MONITORING_IP)" ]; then \
+			echo "[metrics]" >> inventory.ini; \
+			for ip in $$(echo $(MONITORING_IP) | tr ',' ' '); do echo "$$ip ansible_ssh_user=admin ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o ForwardAgent=yes'" >> inventory.ini; done; \
+			echo "" >> inventory.ini; \
+		fi; \
+	else \
+		echo "Error: At least one of DATABASE_IP, EXPLORER_IP, L1_IP, L2_IP, or MONITORING_IP must be set." 1>&2; exit 1; \
+	fi
 
-database:
+database: ## Installs Postgres database
 	ansible-playbook -i inventory.ini database.yml
 
-ethrex-l1:
+ethrex-l1: ## Installs Ethrex L1
+	NETWORK=$(NETWORK)
 	EVM=$(EVM)
 	BOOTNODES=$(BOOTNODES)
 	ansible-playbook -i inventory.ini ethrex-l1.yml
 
-ethrex-l2:
+ethrex-l2: ## Installs Ethrex L2
+	NETWORK=$(NETWORK)
+	GENESIS_JSON_FILE=$(GENESIS_JSON_FILE)
 	COMMON_BRIDGE_ADDRESS=$(COMMON_BRIDGE_ADDRESS)
 	ON_CHAIN_PROPOSER_ADDRESS=$(ON_CHAIN_PROPOSER_ADDRESS)
 	COMMITTER_PK=$(COMMITTER_PK)
@@ -39,7 +58,7 @@ ethrex-l2:
 	INFURA_API_KEY=$(INFURA_API_KEY)
 	ansible-playbook -i inventory.ini ethrex-l2.yml
 
-explorer_backend:
+explorer_backend: ## Installs explorer backend
 	DATABASE_URL=$(DATABASE_URL) # ecto://user:pass@127.0.0.1:5432/db
 	ETHEREUM_JSONRPC_VARIANT=geth
 	ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
@@ -56,8 +75,8 @@ explorer_backend:
 	DISABLE_WEBAPP=true
 	ansible-playbook -i inventory.ini explorer_backend.yml
 
-explorer_fontend:
+explorer_fontend: ## Installs explorer frontend
 	ansible-playbook -i inventory.ini explorer_fontend.yml
 
-metrics:
+metrics: ## Installs grafana and metrics
 	ansible-playbook -i inventory.ini metrics.yml
