Merge main

diff --git a/.github/workflows/common_hive_reports.yaml b/.github/workflows/common_hive_reports.yaml
--- a/.github/workflows/common_hive_reports.yaml
+++ b/.github/workflows/common_hive_reports.yaml
@@ -3,10 +3,10 @@ name: Run Hive Tests
 on:
   workflow_call:
     inputs:
-      # Must be 'main'/'trigger' or 'daily'
       job_type:
         required: true
         type: string
+        description: "Allowed values: 'trigger' or 'daily'"
     outputs:
       report_artifact_name:
         description: "The name of the hive report artifact"
@@ -24,21 +24,13 @@ jobs:
               file_name: rpc-compat,
               simulation: ethereum/rpc-compat,
             }
-          - { 
-              name: "Devp2p eth tests",
-              file_name: devp2p,
-              simulation: devp2p
-            }
+          - { name: "Devp2p eth tests", file_name: devp2p, simulation: devp2p }
           - {
               name: "Cancun Engine tests",
               file_name: engine,
               simulation: ethereum/engine,
             }
-          - {
-              name: "Sync tests",
-              file_name: sync,
-              simulation: ethereum/sync
-            }
+          - { name: "Sync tests", file_name: sync, simulation: ethereum/sync }
           - {
               name: "Consume Engine tests",
               file_name: consume-engine,
@@ -51,25 +43,28 @@ jobs:
             }
 
     steps:
-      - name: Checkout sources
-        if: ${{ inputs.job_type != 'main' }}
-        uses: actions/checkout@v4
+      - name: Verify input parameters
+        if: ${{ inputs.job_type != 'trigger' && inputs.job_type != 'daily' }}
+        run: |
+          echo "Invalid job_type input: ${{ inputs.job_type }}. Allowed values are 'trigger' or 'daily'."
+          exit 1
 
       - name: Checkout sources
-        if: ${{ inputs.job_type == 'main' }}
         uses: actions/checkout@v4
-        with:
-          ref: main
-
-      - name: Build image
-        if: ${{ inputs.job_type != 'main' }}
-        run: make build-image
 
       - name: Pull image
-        if: ${{ inputs.job_type == 'main' }}
+        if: ${{ github.ref_name == 'main' }}
         run: |
-          docker pull ghcr.io/lambdaclass/ethrex:latest
-          docker tag ghcr.io/lambdaclass/ethrex:latest ethrex:latest
+          docker pull ghcr.io/lambdaclass/ethrex:main
+          # Tests use ethrex:ci so we retag it
+          docker tag ghcr.io/lambdaclass/ethrex:main ethrex:ci
+
+      - name: Build image
+        uses: ./.github/actions/build-docker
+        if: ${{ github.ref_name != 'main' }}
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Setup Go
         uses: actions/setup-go@v5
@@ -83,13 +78,13 @@ jobs:
       - name: Set custom hive flags
         run: |
           if [[ "${{ matrix.test.simulation }}" == "ethereum/eest/consume-engine" || "${{ matrix.test.simulation }}" == "ethereum/eest/consume-rlp" ]]; then
-            EEST_FIXTURES=$(cat cmd/ef_tests/blockchain/.fixtures_url)
+            EEST_FIXTURES="https://github.com/ethereum/execution-spec-tests/releases/download/v4.5.0/fixtures_develop.tar.gz"
             EEST_BRANCH=main
             echo 'HIVE_FLAGS=--sim.buildarg fixtures='"$EEST_FIXTURES"' --sim.buildarg branch='"$EEST_BRANCH"' --sim.limit ".*fork_Paris.*|.*fork_Shanghai.*|.*fork_Cancun.*|.*fork_Prague.*"' >> $GITHUB_ENV
           fi
 
       - name: Run Hive Simulation
-        run: cd hive && ./hive --client-file ../fixtures/network/hive_clients/ethrex.yml --client ethrex --sim ${{ matrix.test.simulation }} --sim.parallelism 16 ${{ env.HIVE_FLAGS }} --sim.loglevel 1
+        run: cd hive && ./hive --client-file ../.github/config/hive/clients.yaml --client ethrex --sim ${{ matrix.test.simulation }} --sim.parallelism 16 ${{ env.HIVE_FLAGS }} --sim.loglevel 1
         continue-on-error: true
 
       - name: Upload results
diff --git a/.github/workflows/pr-main_l1.yaml b/.github/workflows/pr-main_l1.yaml
--- a/.github/workflows/pr-main_l1.yaml
+++ b/.github/workflows/pr-main_l1.yaml
@@ -25,6 +25,19 @@ jobs:
         with:
           components: rustfmt, clippy
 
+      - name: Install RISC0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          curl -L https://risczero.com/install | bash
+          ~/.risc0/bin/rzup install cargo-risczero 2.3.1
+          ~/.risc0/bin/rzup install rust
+
+      - name: Create placeholder SP1 ELF
+        run: |
+          mkdir -p crates/l2/prover/zkvm/interface/sp1/out
+          touch crates/l2/prover/zkvm/interface/sp1/out/riscv32im-succinct-zkvm-elf
+
       - name: Run cargo check
         run: cargo check --workspace
 
@@ -32,7 +45,7 @@ jobs:
         run: |
           cargo clippy --workspace -- -D warnings
           cargo clippy -- -D warnings
-          cargo clippy --all-targets --all-features --workspace --exclude ethrex-replay --exclude ethrex-prover --exclude zkvm_interface --exclude ef_tests-blockchain -- -D warnings
+          make lint
 
       - name: Run cargo fmt
         run: |
@@ -54,34 +67,19 @@ jobs:
 
       - name: Run Blockchain EF tests
         run: |
-          make -C cmd/ef_tests/blockchain test
+          make -C tooling/ef_tests/blockchain test
 
   docker_build:
     name: Build Docker
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
+      - id: docker
+        name: Build Ethrex Docker Image
+        uses: ./.github/actions/build-docker
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Build Docker image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: ./Dockerfile
-          load: true
-          tags: ethrex
-          outputs: type=docker,dest=/tmp/ethrex_image.tar
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
@@ -92,12 +90,12 @@ jobs:
     name: "Setup Hive"
     runs-on: ubuntu-latest
     env:
-      HIVE_COMMIT_HASH: 8e8c83f5c5a06561407a6a7848f5a4b32a10a467 # commit from our fork
+      HIVE_COMMIT_HASH: 115f4d6ef1bdd2bfcabe29ec60424f6327e92f43 # commit from our fork
     steps:
       - uses: actions/checkout@v4
       - name: Setup Hive
         run: |
-          git clone --single-branch --branch master https://github.com/lambdaclass/hive
+          git clone --single-branch --branch update_dockerfile https://github.com/lambdaclass/hive
           cd hive
           git checkout --detach ${{ env.HIVE_COMMIT_HASH }}
           go build .
@@ -111,12 +109,14 @@ jobs:
     name: "Setup Hive"
     runs-on: ubuntu-latest
     env:
-      HIVE_COMMIT_HASH: 276ca9deaee8e5831b11fa6e884a9479ee8ca140
+      HIVE_COMMIT_HASH: 115f4d6ef1bdd2bfcabe29ec60424f6327e92f43
     steps:
       - uses: actions/checkout@v4
       - name: Setup Hive
+        # TODO: Change repo back to https://github.com/ethereum/hive when
+        # https://github.com/ethereum/hive/pull/1325 is merged
         run: |
-          git clone --single-branch --branch master https://github.com/ethereum/hive
+          git clone --single-branch --branch update_dockerfile https://github.com/lambdaclass/hive
           cd hive
           git checkout --detach ${{ env.HIVE_COMMIT_HASH }}
           go build .
@@ -186,7 +186,8 @@ jobs:
             test_pattern: discv4|eth|snap/Ping|Findnode/WithoutEndpointProof|Findnode/PastExpiration|Amplification|Status|StorageRanges|ByteCodes|GetBlockHeaders|SimultaneousRequests|SameRequestID|ZeroRequestID|GetBlockBodies|MaliciousHandshake|MaliciousStatus|Transaction|NewPooledTxs|GetBlockReceipts|LargeTxRequest|InvalidTxs
             # AccountRange and GetTrieNodes don't pass anymore.
             #|BlobViolations
-            # Findnode/UnsolicitedNeighbors and Findnode/BasicFindnode flaky in CI very occasionally. When fixed replace all "Findnode/<test>" with "Findnode"
+            # Findnode/BasicFindnode fails due to packets being processed out of order
+            # Findnode/UnsolicitedNeighbors flaky in CI very occasionally. When fixed replace all "Findnode/<test>" with "Findnode"
           - name: "Engine Auth and EC tests"
             simulation: ethereum/engine
             test_pattern: engine-(auth|exchange-capabilities)/
@@ -228,16 +229,40 @@ jobs:
           docker load --input /tmp/ethrex_image.tar
 
       - name: Run Hive Simulation
-        run: chmod +x hive && ./hive --client-file fixtures/network/hive_clients/ethrex.yml --client ethrex --sim ${{ matrix.simulation }} --sim.limit "${{ matrix.test_pattern }}" --sim.parallelism 16 --sim.loglevel 1
+        run: chmod +x hive && ./hive --client-file .github/config/hive/clients.yaml --client ethrex --sim ${{ matrix.simulation }} --sim.limit "${{ matrix.test_pattern }}" --sim.parallelism 16 --sim.loglevel 1
+
+  run-replay:
+    name: Execute an L1 block
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v4
+      - name: Setup Rust Environment
+        uses: ./.github/actions/setup-rust
+
+      - name: Build
+        run: |
+          cd cmd/ethrex_replay
+          cargo b -r
+
+      - name: Run
+        env:
+          # TODO(): use RPC
+          # RPC_URL: $${{ secrets.ETHREX_L2_RPC_URL }}
+          RPC_URL: "http://45.76.185.153:8545"
+        run: |
+          cp fixtures/cache/rpc_prover/cache_hoodi_1132599.bin cmd/ethrex_replay
+          cd cmd/ethrex_replay
+          make execute BLOCK_NUMBER=1132599 NETWORK=hoodi
 
   # The purpose of this job is to add it as a required check in GitHub so that we don't have to add every individual job as a required check
   all-tests:
     # "Integration Test" is a required check, don't change the name
     name: Integration Test
     runs-on: ubuntu-latest
-    needs: [run-assertoor, run-hive]
+    needs: [run-assertoor, run-hive, run-replay]
     # Make sure this job runs even if the previous jobs failed or were skipped
-    if: ${{ always() && needs.run-assertoor.result != 'skipped' && needs.run-hive.result != 'skipped' }}
+    if: ${{ always() && needs.run-assertoor.result != 'skipped' && needs.run-hive.result != 'skipped' && needs.run-replay.result != 'skipped' }}
     steps:
       - name: Check if any job failed
         run: |
@@ -248,5 +273,10 @@ jobs:
 
           if [ "${{ needs.run-hive.result }}" != "success" ]; then
             echo "Job Hive failed"
+            exit 1
+          fi
+
+          if [ "${{ needs.run-replay.result }}" != "success" ]; then
+            echo "Job Replay failed"
             exit 1
           fi
