fix address contract?

diff --git a/.github/workflows/pr-main_l2.yaml b/.github/workflows/pr-main_l2.yaml
--- a/.github/workflows/pr-main_l2.yaml
+++ b/.github/workflows/pr-main_l2.yaml
@@ -203,6 +203,7 @@ jobs:
           ETHREX_DEPLOYER_RISC0_CONTRACT_ADDRESS=0x00000000000000000000000000000000000000aa \
           ETHREX_DEPLOYER_DEPLOY_BASED_CONTRACTS=true \
           docker compose -f docker-compose-l2.yaml up contract_deployer
+          echo $ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS
 
       - name: Install rex
         run: |
@@ -217,12 +218,10 @@ jobs:
       - name: Register sequencer
         run: |
           rex send 0xa2f9240e897184ff79ed027ea1f0cf1bae718957 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
+          rex call 0xa2f9240e897184ff79ed027ea1f0cf1bae718957 -- "leaderSequencer()"
 
       - name: Start Sequencer
         run: |
-          pwd
-          rustup install 1.82.0 # Install the specific toolchain needed by ethrex
-          rustup default 1.82.0
           cd crates/l2
           CI_ETHREX_WORKDIR=/usr/local/bin \
           ETHREX_COMMITTER_VALIDIUM=false \
@@ -292,9 +291,9 @@ jobs:
     # "Integration Test" is a required check, don't change the name
     name: Integration Test
     runs-on: ubuntu-latest
-    needs: [integration-test, state-diff-test] # ADD HERE NEW TEST BEFORE MERGING, not now for fast checking
+    needs: [integration-test, state-diff-test, integration-test-based]
     # Make sure this job runs even if the previous jobs failed or were skipped
-    if: ${{ always() && needs.integration-test.result != 'skipped' && needs.state-diff-test.result != 'skipped' }}
+    if: ${{ always() && needs.integration-test.result != 'skipped' && needs.state-diff-test.result != 'skipped' && needs.integration-test-based.result != 'skipped' }}
     steps:
       - name: Check if any job failed
         run: |
@@ -305,5 +304,10 @@ jobs:
 
           if [ "${{ needs.state-diff-test.result }}" != "success" ]; then
             echo "Job State Reconstruction Tests failed"
+            exit 1
+          fi
+
+          if [ "${{ needs.integration-test-based.result }}" != "success" ]; then
+            echo "Job Integration Tests Based failed"
             exit 1
           fi
