use correct change

diff --git a/.github/workflows/pr-main_l2.yaml b/.github/workflows/pr-main_l2.yaml
--- a/.github/workflows/pr-main_l2.yaml
+++ b/.github/workflows/pr-main_l2.yaml
@@ -184,27 +184,28 @@ jobs:
       - name: Register sequencer
         run: |
           cd crates/l2
-          SEQUENCER_REGISTRY=$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)
-          export SEQUENCER_REGISTRY
-
-          if [ -z "$SEQUENCER_REGISTRY" ]; then
-            echo "Failed to get SEQUENCER_REGISTRY from .env file"
+          source .env
+          if [ -z "$ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS" ]; then
+            echo "Failed to get ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS from .env file"
             exit 1
           fi
-          rex send "$SEQUENCER_REGISTRY" 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
-          rex call "$SEQUENCER_REGISTRY" -- "leaderSequencer()"
+          rex send "$ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS" 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
+          rex call "$ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS" -- "leaderSequencer()"
 
       - name: Start Sequencer
         run: |
           cd crates/l2
-          SEQUENCER_REGISTRY=$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)
-          export SEQUENCER_REGISTRY
+          source .env
+          if [ -z "$ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS" ]; then
+            echo "Failed to get ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS from .env file"
+            exit 1
+          fi
 
           CI_ETHREX_WORKDIR=/usr/local/bin \
           ETHREX_COMMITTER_VALIDIUM=false \
           ETHREX_WATCHER_BLOCK_DELAY=0 \
           ETHREX_BASED=true \
-          ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY="$SEQUENCER_REGISTRY" \
+          ETHREX_STATE_UPDATER_SEQUENCER_REGISTRY="$ETHREX_DEPLOYER_SEQUENCER_REGISTRY_ADDRESS" \
           docker compose -f docker-compose-l2.yaml up --detach ethrex_l2
 
       - name: Run test
