try fix ci

diff --git a/.github/workflows/pr-main_l2.yaml b/.github/workflows/pr-main_l2.yaml
--- a/.github/workflows/pr-main_l2.yaml
+++ b/.github/workflows/pr-main_l2.yaml
@@ -217,9 +217,15 @@ jobs:
       - name: Register sequencer
         run: |
           cd crates/l2
-          export SEQUENCER_REGISTRY="$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)"
-          rex send $SEQUENCER_REGISTRY 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
-          rex call $SEQUENCER_REGISTRY -- "leaderSequencer()"
+          SEQUENCER_REGISTRY=$(grep ETHREX_DEPLOYER_SEQUENCER_REGISTRY .env | cut -d= -f2)
+          export SEQUENCER_REGISTRY
+          
+          if [ -z "$SEQUENCER_REGISTRY" ]; then
+            echo "Failed to get SEQUENCER_REGISTRY from .env file"
+            exit 1
+          fi
+          rex send "$SEQUENCER_REGISTRY" 1000000000000000000 0x385c546456b6a603a1cfcaa9ec9494ba4832da08dd6bcf4de9a71e4a01b74924 -- "register(address)" 0x3d1e15a1a55578f7c920884a9943b3b35d0d885b
+          rex call "$SEQUENCER_REGISTRY" -- "leaderSequencer()"
 
       - name: Start Sequencer
         run: |
